name: digitharium
services:
  keycloak:
    container_name: digitharium_keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "53531:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMINPASSWORD: "admin"
    command:
      - start-dev
  drupal:
    container_name: digitharium_drupal
    image: drupal
    ports:
      - "8081:80"
    environment:
      DB_HOST: "drupal_mysql"
      DB_USER: "user"
      DB_PASS: "password"
    # env_file:
      # - .env-drupal
    volumes:
      - ./config:/var/config
    depends_on:
      - drupal_mysql
#DBs
  drupal_mysql:
    container_name: digitharium_drupal_mysql
    image: container-registry.oracle.com/mysql/community-server
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "drupal_mysql"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - database:/var/lib/myqsql
    ports:
      - "3306:3306"
volumes:
  database: